// Code generated by protoc-gen-go. DO NOT EDIT.
// source: schema.proto

/*
Package main is a generated protocol buffer package.

It is generated from these files:
	schema.proto

It has these top-level messages:
	RequestParams
	ResponseRoot
	RequestRoot
	Payload
	NewsData
	NewsBody
	NewsSource
	Cover
	CoverImage
	CoverVideo
	SimilarRequest
	RequestLocale
	Device
*/
package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RequestParams struct {
	Keyword          *string `protobuf:"bytes,2,opt,name=keyword" json:"keyword,omitempty"`
	SomeId           *int64  `protobuf:"varint,5,opt,name=someId" json:"someId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RequestParams) Reset()                    { *m = RequestParams{} }
func (m *RequestParams) String() string            { return proto.CompactTextString(m) }
func (*RequestParams) ProtoMessage()               {}
func (*RequestParams) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RequestParams) GetKeyword() string {
	if m != nil && m.Keyword != nil {
		return *m.Keyword
	}
	return ""
}

func (m *RequestParams) GetSomeId() int64 {
	if m != nil && m.SomeId != nil {
		return *m.SomeId
	}
	return 0
}

type ResponseRoot struct {
	Payload          *Payload `protobuf:"bytes,1,opt,name=payload" json:"payload,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *ResponseRoot) Reset()                    { *m = ResponseRoot{} }
func (m *ResponseRoot) String() string            { return proto.CompactTextString(m) }
func (*ResponseRoot) ProtoMessage()               {}
func (*ResponseRoot) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ResponseRoot) GetPayload() *Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

type RequestRoot struct {
	Device           *Device        `protobuf:"bytes,1,opt,name=device" json:"device,omitempty"`
	Params           *RequestParams `protobuf:"bytes,2,opt,name=params" json:"params,omitempty"`
	Count            *int64         `protobuf:"varint,11,opt,name=count" json:"count,omitempty"`
	Locale           *RequestLocale `protobuf:"bytes,13,opt,name=locale" json:"locale,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *RequestRoot) Reset()                    { *m = RequestRoot{} }
func (m *RequestRoot) String() string            { return proto.CompactTextString(m) }
func (*RequestRoot) ProtoMessage()               {}
func (*RequestRoot) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *RequestRoot) GetDevice() *Device {
	if m != nil {
		return m.Device
	}
	return nil
}

func (m *RequestRoot) GetParams() *RequestParams {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *RequestRoot) GetCount() int64 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

func (m *RequestRoot) GetLocale() *RequestLocale {
	if m != nil {
		return m.Locale
	}
	return nil
}

type Payload struct {
	Request          *RequestParams `protobuf:"bytes,1,opt,name=request" json:"request,omitempty"`
	Data             []*NewsData    `protobuf:"bytes,2,rep,name=data" json:"data,omitempty"`
	GoogleUrl        *string        `protobuf:"bytes,17,opt,name=googleUrl" json:"googleUrl,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *Payload) Reset()                    { *m = Payload{} }
func (m *Payload) String() string            { return proto.CompactTextString(m) }
func (*Payload) ProtoMessage()               {}
func (*Payload) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Payload) GetRequest() *RequestParams {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *Payload) GetData() []*NewsData {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Payload) GetGoogleUrl() string {
	if m != nil && m.GoogleUrl != nil {
		return *m.GoogleUrl
	}
	return ""
}

type NewsData struct {
	Token            *string        `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	Body             *NewsBody      `protobuf:"bytes,2,opt,name=body" json:"body,omitempty"`
	Timestamp        *int64         `protobuf:"varint,6,opt,name=timestamp" json:"timestamp,omitempty"`
	Keyword          *string        `protobuf:"bytes,11,opt,name=keyword" json:"keyword,omitempty"`
	ImageUrl         *string        `protobuf:"bytes,12,opt,name=imageUrl" json:"imageUrl,omitempty"`
	SomeId           *int64         `protobuf:"varint,14,opt,name=someId" json:"someId,omitempty"`
	Request          *RequestParams `protobuf:"bytes,17,opt,name=request" json:"request,omitempty"`
	SomeId2          *int64         `protobuf:"varint,1002,opt,name=someId2" json:"someId2,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *NewsData) Reset()                    { *m = NewsData{} }
func (m *NewsData) String() string            { return proto.CompactTextString(m) }
func (*NewsData) ProtoMessage()               {}
func (*NewsData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *NewsData) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

func (m *NewsData) GetBody() *NewsBody {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *NewsData) GetTimestamp() int64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *NewsData) GetKeyword() string {
	if m != nil && m.Keyword != nil {
		return *m.Keyword
	}
	return ""
}

func (m *NewsData) GetImageUrl() string {
	if m != nil && m.ImageUrl != nil {
		return *m.ImageUrl
	}
	return ""
}

func (m *NewsData) GetSomeId() int64 {
	if m != nil && m.SomeId != nil {
		return *m.SomeId
	}
	return 0
}

func (m *NewsData) GetRequest() *RequestParams {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *NewsData) GetSomeId2() int64 {
	if m != nil && m.SomeId2 != nil {
		return *m.SomeId2
	}
	return 0
}

type NewsBody struct {
	Id               *int64      `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Title            *string     `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	Source           *NewsSource `protobuf:"bytes,3,opt,name=source" json:"source,omitempty"`
	Timestamp        *int64      `protobuf:"varint,4,opt,name=timestamp" json:"timestamp,omitempty"`
	Body             *string     `protobuf:"bytes,5,opt,name=body" json:"body,omitempty"`
	SourceUrl        *string     `protobuf:"bytes,6,opt,name=sourceUrl" json:"sourceUrl,omitempty"`
	Cover            *Cover      `protobuf:"bytes,9,opt,name=cover" json:"cover,omitempty"`
	PreviewImageUrl  *string     `protobuf:"bytes,12,opt,name=previewImageUrl" json:"previewImageUrl,omitempty"`
	Token            *string     `protobuf:"bytes,14,opt,name=token" json:"token,omitempty"`
	SomeNumber       *int64      `protobuf:"varint,24,opt,name=someNumber" json:"someNumber,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *NewsBody) Reset()                    { *m = NewsBody{} }
func (m *NewsBody) String() string            { return proto.CompactTextString(m) }
func (*NewsBody) ProtoMessage()               {}
func (*NewsBody) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *NewsBody) GetId() int64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *NewsBody) GetTitle() string {
	if m != nil && m.Title != nil {
		return *m.Title
	}
	return ""
}

func (m *NewsBody) GetSource() *NewsSource {
	if m != nil {
		return m.Source
	}
	return nil
}

func (m *NewsBody) GetTimestamp() int64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func (m *NewsBody) GetBody() string {
	if m != nil && m.Body != nil {
		return *m.Body
	}
	return ""
}

func (m *NewsBody) GetSourceUrl() string {
	if m != nil && m.SourceUrl != nil {
		return *m.SourceUrl
	}
	return ""
}

func (m *NewsBody) GetCover() *Cover {
	if m != nil {
		return m.Cover
	}
	return nil
}

func (m *NewsBody) GetPreviewImageUrl() string {
	if m != nil && m.PreviewImageUrl != nil {
		return *m.PreviewImageUrl
	}
	return ""
}

func (m *NewsBody) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

func (m *NewsBody) GetSomeNumber() int64 {
	if m != nil && m.SomeNumber != nil {
		return *m.SomeNumber
	}
	return 0
}

type NewsSource struct {
	Title            *string `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *NewsSource) Reset()                    { *m = NewsSource{} }
func (m *NewsSource) String() string            { return proto.CompactTextString(m) }
func (*NewsSource) ProtoMessage()               {}
func (*NewsSource) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *NewsSource) GetTitle() string {
	if m != nil && m.Title != nil {
		return *m.Title
	}
	return ""
}

type Cover struct {
	Image            *CoverImage `protobuf:"bytes,3,opt,name=image" json:"image,omitempty"`
	Video            *CoverVideo `protobuf:"bytes,4,opt,name=video" json:"video,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *Cover) Reset()                    { *m = Cover{} }
func (m *Cover) String() string            { return proto.CompactTextString(m) }
func (*Cover) ProtoMessage()               {}
func (*Cover) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Cover) GetImage() *CoverImage {
	if m != nil {
		return m.Image
	}
	return nil
}

func (m *Cover) GetVideo() *CoverVideo {
	if m != nil {
		return m.Video
	}
	return nil
}

type CoverImage struct {
	Url              *string `protobuf:"bytes,4,opt,name=url" json:"url,omitempty"`
	Width            *int64  `protobuf:"varint,5,opt,name=width" json:"width,omitempty"`
	Height           *int64  `protobuf:"varint,6,opt,name=height" json:"height,omitempty"`
	SomeNumber       *int64  `protobuf:"varint,7,opt,name=someNumber" json:"someNumber,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CoverImage) Reset()                    { *m = CoverImage{} }
func (m *CoverImage) String() string            { return proto.CompactTextString(m) }
func (*CoverImage) ProtoMessage()               {}
func (*CoverImage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *CoverImage) GetUrl() string {
	if m != nil && m.Url != nil {
		return *m.Url
	}
	return ""
}

func (m *CoverImage) GetWidth() int64 {
	if m != nil && m.Width != nil {
		return *m.Width
	}
	return 0
}

func (m *CoverImage) GetHeight() int64 {
	if m != nil && m.Height != nil {
		return *m.Height
	}
	return 0
}

func (m *CoverImage) GetSomeNumber() int64 {
	if m != nil && m.SomeNumber != nil {
		return *m.SomeNumber
	}
	return 0
}

type CoverVideo struct {
	Url              *string `protobuf:"bytes,4,opt,name=url" json:"url,omitempty"`
	Width            *int64  `protobuf:"varint,5,opt,name=width" json:"width,omitempty"`
	Height           *int64  `protobuf:"varint,6,opt,name=height" json:"height,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CoverVideo) Reset()                    { *m = CoverVideo{} }
func (m *CoverVideo) String() string            { return proto.CompactTextString(m) }
func (*CoverVideo) ProtoMessage()               {}
func (*CoverVideo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *CoverVideo) GetUrl() string {
	if m != nil && m.Url != nil {
		return *m.Url
	}
	return ""
}

func (m *CoverVideo) GetWidth() int64 {
	if m != nil && m.Width != nil {
		return *m.Width
	}
	return 0
}

func (m *CoverVideo) GetHeight() int64 {
	if m != nil && m.Height != nil {
		return *m.Height
	}
	return 0
}

type SimilarRequest struct {
	Keyword1         *string `protobuf:"bytes,1,opt,name=keyword1" json:"keyword1,omitempty"`
	Keyword2         *string `protobuf:"bytes,2,opt,name=keyword2" json:"keyword2,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SimilarRequest) Reset()                    { *m = SimilarRequest{} }
func (m *SimilarRequest) String() string            { return proto.CompactTextString(m) }
func (*SimilarRequest) ProtoMessage()               {}
func (*SimilarRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *SimilarRequest) GetKeyword1() string {
	if m != nil && m.Keyword1 != nil {
		return *m.Keyword1
	}
	return ""
}

func (m *SimilarRequest) GetKeyword2() string {
	if m != nil && m.Keyword2 != nil {
		return *m.Keyword2
	}
	return ""
}

type RequestLocale struct {
	Lang             *string `protobuf:"bytes,4,opt,name=lang" json:"lang,omitempty"`
	Country          *string `protobuf:"bytes,5,opt,name=country" json:"country,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RequestLocale) Reset()                    { *m = RequestLocale{} }
func (m *RequestLocale) String() string            { return proto.CompactTextString(m) }
func (*RequestLocale) ProtoMessage()               {}
func (*RequestLocale) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *RequestLocale) GetLang() string {
	if m != nil && m.Lang != nil {
		return *m.Lang
	}
	return ""
}

func (m *RequestLocale) GetCountry() string {
	if m != nil && m.Country != nil {
		return *m.Country
	}
	return ""
}

type Device struct {
	Lang             *string `protobuf:"bytes,8,opt,name=lang" json:"lang,omitempty"`
	Country          *string `protobuf:"bytes,9,opt,name=country" json:"country,omitempty"`
	SetOne           *int64  `protobuf:"varint,17,opt,name=setOne" json:"setOne,omitempty"`
	SetOne2          *int64  `protobuf:"varint,18,opt,name=setOne2" json:"setOne2,omitempty"`
	SetOne3          *int64  `protobuf:"varint,20,opt,name=setOne3" json:"setOne3,omitempty"`
	Token            *string `protobuf:"bytes,21,opt,name=token" json:"token,omitempty"`
	DeviceId         *string `protobuf:"bytes,24,opt,name=deviceId" json:"deviceId,omitempty"`
	SomeStringId     *string `protobuf:"bytes,25,opt,name=someStringId" json:"someStringId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Device) Reset()                    { *m = Device{} }
func (m *Device) String() string            { return proto.CompactTextString(m) }
func (*Device) ProtoMessage()               {}
func (*Device) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *Device) GetLang() string {
	if m != nil && m.Lang != nil {
		return *m.Lang
	}
	return ""
}

func (m *Device) GetCountry() string {
	if m != nil && m.Country != nil {
		return *m.Country
	}
	return ""
}

func (m *Device) GetSetOne() int64 {
	if m != nil && m.SetOne != nil {
		return *m.SetOne
	}
	return 0
}

func (m *Device) GetSetOne2() int64 {
	if m != nil && m.SetOne2 != nil {
		return *m.SetOne2
	}
	return 0
}

func (m *Device) GetSetOne3() int64 {
	if m != nil && m.SetOne3 != nil {
		return *m.SetOne3
	}
	return 0
}

func (m *Device) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

func (m *Device) GetDeviceId() string {
	if m != nil && m.DeviceId != nil {
		return *m.DeviceId
	}
	return ""
}

func (m *Device) GetSomeStringId() string {
	if m != nil && m.SomeStringId != nil {
		return *m.SomeStringId
	}
	return ""
}

func init() {
	proto.RegisterType((*RequestParams)(nil), "main.RequestParams")
	proto.RegisterType((*ResponseRoot)(nil), "main.ResponseRoot")
	proto.RegisterType((*RequestRoot)(nil), "main.RequestRoot")
	proto.RegisterType((*Payload)(nil), "main.Payload")
	proto.RegisterType((*NewsData)(nil), "main.NewsData")
	proto.RegisterType((*NewsBody)(nil), "main.NewsBody")
	proto.RegisterType((*NewsSource)(nil), "main.NewsSource")
	proto.RegisterType((*Cover)(nil), "main.Cover")
	proto.RegisterType((*CoverImage)(nil), "main.CoverImage")
	proto.RegisterType((*CoverVideo)(nil), "main.CoverVideo")
	proto.RegisterType((*SimilarRequest)(nil), "main.SimilarRequest")
	proto.RegisterType((*RequestLocale)(nil), "main.RequestLocale")
	proto.RegisterType((*Device)(nil), "main.Device")
}

func init() { proto.RegisterFile("schema.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 602 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x95, 0x9b, 0x26, 0xae, 0xc7, 0x4e, 0xda, 0x98, 0x22, 0x16, 0xa8, 0x20, 0x32, 0x1c, 0x72,
	0x8a, 0xc0, 0x70, 0xe0, 0x0c, 0xbd, 0x44, 0xaa, 0x4a, 0xd5, 0x0a, 0xce, 0x6c, 0xe3, 0x91, 0xb3,
	0xaa, 0xed, 0x35, 0xeb, 0x4d, 0xa2, 0xdc, 0xf9, 0x00, 0x7e, 0x86, 0x2f, 0xe1, 0x2f, 0xf8, 0x0a,
	0xb4, 0xb3, 0x5b, 0x37, 0xae, 0xca, 0x81, 0xa3, 0x67, 0xdf, 0xbe, 0x79, 0x6f, 0xdf, 0x8c, 0x21,
	0x6a, 0x16, 0x4b, 0x2c, 0xf9, 0xac, 0x56, 0x52, 0xcb, 0x78, 0xbf, 0xe4, 0xa2, 0x4a, 0xde, 0xc0,
	0xf0, 0x12, 0xbf, 0xaf, 0xb0, 0xd1, 0x17, 0x5c, 0xf1, 0xb2, 0x89, 0x0f, 0xc1, 0xbf, 0xc1, 0xed,
	0x46, 0xaa, 0x8c, 0xed, 0x4d, 0xbc, 0x69, 0x10, 0x8f, 0x60, 0xd0, 0xc8, 0x12, 0xe7, 0x19, 0xeb,
	0x4f, 0xbc, 0x69, 0x2f, 0x99, 0x41, 0x74, 0x89, 0x4d, 0x2d, 0xab, 0x06, 0x2f, 0xa5, 0xd4, 0xf1,
	0x0b, 0xf0, 0x6b, 0xbe, 0x2d, 0x24, 0xcf, 0x98, 0x37, 0xf1, 0xa6, 0x61, 0x3a, 0x9c, 0x19, 0xe6,
	0xd9, 0x85, 0x2d, 0x26, 0x3f, 0x3c, 0x08, 0x5d, 0x0b, 0xc2, 0x9f, 0xc0, 0x20, 0xc3, 0xb5, 0x58,
	0xa0, 0x83, 0x47, 0x16, 0x7e, 0x4a, 0xb5, 0xf8, 0x15, 0x0c, 0x6a, 0x12, 0x42, 0xdd, 0xc3, 0xf4,
	0x91, 0x3d, 0xed, 0x6a, 0x1c, 0x42, 0x7f, 0x21, 0x57, 0x95, 0x66, 0xa1, 0x51, 0x64, 0xee, 0x14,
	0x72, 0xc1, 0x0b, 0x64, 0xc3, 0x07, 0xee, 0x9c, 0xd1, 0x51, 0xf2, 0x0d, 0x7c, 0xa7, 0x28, 0x7e,
	0x0d, 0xbe, 0xb2, 0x67, 0x4e, 0xc2, 0x83, 0x4d, 0x4e, 0x60, 0x3f, 0xe3, 0x9a, 0xb3, 0xbd, 0x49,
	0x6f, 0x1a, 0xa6, 0x23, 0x0b, 0x39, 0xc7, 0x4d, 0x73, 0xca, 0x35, 0x8f, 0xc7, 0x10, 0xe4, 0x52,
	0xe6, 0x05, 0x7e, 0x51, 0x05, 0x1b, 0x9b, 0x87, 0x4a, 0x7e, 0x79, 0x70, 0xd0, 0x9e, 0x0f, 0xa1,
	0xaf, 0xe5, 0x0d, 0x56, 0xd4, 0x21, 0x30, 0x64, 0xd7, 0x32, 0xdb, 0x3a, 0x53, 0x3b, 0x64, 0x1f,
	0x65, 0xb6, 0x35, 0x64, 0x5a, 0x94, 0xd8, 0x68, 0x5e, 0xd6, 0x6c, 0x40, 0x9e, 0x76, 0x62, 0x08,
	0x89, 0xe1, 0x08, 0x0e, 0x44, 0xc9, 0x73, 0xea, 0x17, 0xdd, 0x0b, 0x66, 0x44, 0x57, 0x76, 0x6c,
	0x8d, 0xff, 0x6d, 0xeb, 0x08, 0x7c, 0x7b, 0x2b, 0x65, 0x7f, 0x7c, 0x0a, 0xf4, 0xb7, 0xd3, 0x4d,
	0x52, 0x00, 0xf6, 0x84, 0x0d, 0xb2, 0x47, 0x1e, 0x84, 0x2e, 0xd0, 0x0d, 0xc2, 0xc4, 0xf4, 0x5b,
	0xa9, 0x05, 0xb2, 0x1e, 0xd1, 0x1f, 0xdd, 0xb9, 0xb8, 0xa2, 0x7a, 0xd7, 0xc7, 0x3e, 0x71, 0x44,
	0xce, 0x78, 0x9f, 0x28, 0xc6, 0x10, 0x58, 0x0a, 0xe3, 0x62, 0x40, 0xa5, 0x67, 0x26, 0xcb, 0x35,
	0x2a, 0x16, 0x10, 0x69, 0x68, 0x49, 0x3f, 0x99, 0x52, 0xfc, 0x04, 0x0e, 0x6b, 0x85, 0x6b, 0x81,
	0x9b, 0x79, 0xd7, 0x7a, 0xfb, 0xba, 0x23, 0xfa, 0x8c, 0x01, 0x8c, 0xa7, 0xf3, 0x55, 0x79, 0x8d,
	0x8a, 0x31, 0x72, 0xf5, 0x1c, 0x60, 0x47, 0x59, 0x6b, 0x85, 0xe2, 0x48, 0xe6, 0xd0, 0xb7, 0x1d,
	0x5e, 0x42, 0x9f, 0x5e, 0xb5, 0x6b, 0x89, 0xce, 0xa8, 0xa5, 0x01, 0xac, 0x45, 0x86, 0x92, 0xec,
	0x74, 0x01, 0x5f, 0x4d, 0x3d, 0x39, 0x03, 0xd8, 0x81, 0x87, 0xd0, 0x5b, 0xa9, 0x82, 0xc0, 0xa4,
	0x72, 0x23, 0x32, 0xbd, 0xb4, 0x8b, 0x63, 0xf2, 0x5a, 0xa2, 0xc8, 0x97, 0xda, 0x45, 0xdc, 0x55,
	0x6d, 0xb3, 0xf8, 0xe0, 0xd8, 0x88, 0xfb, 0x7f, 0xd8, 0x92, 0xf7, 0x30, 0xba, 0x12, 0xa5, 0x28,
	0xb8, 0x72, 0x79, 0x9b, 0x89, 0x71, 0x23, 0xf4, 0xd6, 0x4d, 0xe1, 0x5d, 0x25, 0xb5, 0x99, 0x26,
	0xb3, 0x76, 0xfd, 0xed, 0x9a, 0x98, 0xbc, 0x0a, 0x5e, 0xe5, 0xae, 0xe7, 0x21, 0xf8, 0xb4, 0x68,
	0xca, 0x05, 0x98, 0xfc, 0xf4, 0x60, 0xe0, 0x36, 0xf5, 0x16, 0x79, 0x70, 0x1f, 0x19, 0xb4, 0xd3,
	0x89, 0xfa, 0x73, 0x85, 0x34, 0x8c, 0x34, 0xd0, 0xf6, 0x3b, 0x65, 0x71, 0xb7, 0xf0, 0x8e, 0x1d,
	0xb7, 0xe3, 0x46, 0xa1, 0x3e, 0xbe, 0x15, 0x6b, 0xff, 0x13, 0xf3, 0x8c, 0x22, 0x0d, 0xe2, 0x63,
	0x88, 0xcc, 0x83, 0x5d, 0x69, 0x25, 0xaa, 0x7c, 0x9e, 0xb1, 0xa7, 0xa6, 0xfa, 0x37, 0x00, 0x00,
	0xff, 0xff, 0x1a, 0x2d, 0x98, 0x5c, 0xd6, 0x04, 0x00, 0x00,
}
